# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVCDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'Moya'
  pod 'RxSwift'
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'CryptoSwift'
  pod 'CodableAlamofire'
  pod 'MBProgressHUD'
  
  #### codable
  pod 'LKDBHelper'
  pod "SugarRecord/CoreData"
  pod "SugarRecord/CoreData+iCloud"
  
  # Pods for MVCDemo

  target 'MVCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
