# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkLayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxOptional'
    pod 'Moya/RxSwift'
    pod 'NSObject+Rx'
    pod 'Action'
    pod 'ReachabilitySwift'
    pod 'CryptoSwift'
    pod 'NSObject+Rx'
#    pod 'Result'

  # Pods for NetworkLayer

  target 'NetworkLayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkLayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
